version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: foxbase_backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ui_interface.Dockerfile
    container_name: foxbase_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
